# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Empleado(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, nombre: str=None, apellido: str=None, email: str=None, telefono: str=None, ocupacin: str=None, eps: str=None, arl: str=None):  # noqa: E501
        """Empleado - a model defined in Swagger

        :param id: The id of this Empleado.  # noqa: E501
        :type id: int
        :param nombre: The nombre of this Empleado.  # noqa: E501
        :type nombre: str
        :param apellido: The apellido of this Empleado.  # noqa: E501
        :type apellido: str
        :param email: The email of this Empleado.  # noqa: E501
        :type email: str
        :param telefono: The telefono of this Empleado.  # noqa: E501
        :type telefono: str
        :param ocupacin: The ocupacin of this Empleado.  # noqa: E501
        :type ocupacin: str
        :param eps: The eps of this Empleado.  # noqa: E501
        :type eps: str
        :param arl: The arl of this Empleado.  # noqa: E501
        :type arl: str
        """
        self.swagger_types = {
            'id': int,
            'nombre': str,
            'apellido': str,
            'email': str,
            'telefono': str,
            'ocupacin': str,
            'eps': str,
            'arl': str
        }

        self.attribute_map = {
            'id': 'id',
            'nombre': 'nombre',
            'apellido': 'apellido',
            'email': 'email',
            'telefono': 'telefono',
            'ocupacin': 'ocupación',
            'eps': 'eps',
            'arl': 'arl'
        }

        self._id = id
        self._nombre = nombre
        self._apellido = apellido
        self._email = email
        self._telefono = telefono
        self._ocupacin = ocupacin
        self._eps = eps
        self._arl = arl

    @classmethod
    def from_dict(cls, dikt) -> 'Empleado':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Empleado of this Empleado.  # noqa: E501
        :rtype: Empleado
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Empleado.


        :return: The id of this Empleado.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Empleado.


        :param id: The id of this Empleado.
        :type id: int
        """

        self._id = id

    @property
    def nombre(self) -> str:
        """Gets the nombre of this Empleado.


        :return: The nombre of this Empleado.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """Sets the nombre of this Empleado.


        :param nombre: The nombre of this Empleado.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def apellido(self) -> str:
        """Gets the apellido of this Empleado.


        :return: The apellido of this Empleado.
        :rtype: str
        """
        return self._apellido

    @apellido.setter
    def apellido(self, apellido: str):
        """Sets the apellido of this Empleado.


        :param apellido: The apellido of this Empleado.
        :type apellido: str
        """

        self._apellido = apellido

    @property
    def email(self) -> str:
        """Gets the email of this Empleado.


        :return: The email of this Empleado.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Empleado.


        :param email: The email of this Empleado.
        :type email: str
        """

        self._email = email

    @property
    def telefono(self) -> str:
        """Gets the telefono of this Empleado.


        :return: The telefono of this Empleado.
        :rtype: str
        """
        return self._telefono

    @telefono.setter
    def telefono(self, telefono: str):
        """Sets the telefono of this Empleado.


        :param telefono: The telefono of this Empleado.
        :type telefono: str
        """

        self._telefono = telefono

    @property
    def ocupacin(self) -> str:
        """Gets the ocupacin of this Empleado.


        :return: The ocupacin of this Empleado.
        :rtype: str
        """
        return self._ocupacin

    @ocupacin.setter
    def ocupacin(self, ocupacin: str):
        """Sets the ocupacin of this Empleado.


        :param ocupacin: The ocupacin of this Empleado.
        :type ocupacin: str
        """

        self._ocupacin = ocupacin

    @property
    def eps(self) -> str:
        """Gets the eps of this Empleado.


        :return: The eps of this Empleado.
        :rtype: str
        """
        return self._eps

    @eps.setter
    def eps(self, eps: str):
        """Sets the eps of this Empleado.


        :param eps: The eps of this Empleado.
        :type eps: str
        """

        self._eps = eps

    @property
    def arl(self) -> str:
        """Gets the arl of this Empleado.


        :return: The arl of this Empleado.
        :rtype: str
        """
        return self._arl

    @arl.setter
    def arl(self, arl: str):
        """Sets the arl of this Empleado.


        :param arl: The arl of this Empleado.
        :type arl: str
        """

        self._arl = arl
